services:
  pokemon-monitor:
    build: .
    container_name: pokemon-monitor
    restart: unless-stopped
    env_file:
      - .env
    environment:
      STATE_FILE: /app/data/.state.json
      TZ: Asia/Jakarta
      PYTHONIOENCODING: utf-8
    volumes:
      - ./config.json:/app/config.json:ro
      - ./data:/app/data
